### ISSUE TITLE
Get *-labels.txt for all languages

### ISSUE THREAD

**Issue by amundo** [amundo/comparative-fulani#3]
like you did for `ffm-labels.txt`

**Comment by morrisonhannah** [comment]
Almost done -- done for ffm, fub, fuv, fuh, but not yet for fuc, fuf which may or may not be the longest recordings at 10 and 7 minutes respectively :,) and the auto segmentation is really not helping since there's English interspersed everywhere. Not sure if manually segmenting them will be the answer, rather than spending time correcting auto transcriber's mistakes? But the audacity segmentation workflow is not very comfortable from what I tested

**Comment by amundo** [comment]
The English is ok because we can make our interface help skip them

**Comment by amundo** [comment]
Also, good work keep it up!

**Comment by morrisonhannah** [comment]
Ah i remembered that the issue is moreso that there is a somewhat continuous stream of english and fulani (fuf) back and forth and audacity is having trouble segmenting it, giving me large chunks that would need to be painstakingly trimmed and split rather than just deleting/selecting out the english annotations
I can still do it but just got burnt out the other day and wanna figure out if there's a less painstaking way

**Comment by morrisonhannah** [comment]
i can think of ways now that i have a fresh mind

**Comment by morrisonhannah** [comment]
Yay, finished those last two
